baseURL: https://example.com/
title: WSL2 RStudio-Server
theme: hugo-book
disablePathToLower: yes
enableGitInfo: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
  tableOfContents:
    startLevel: 1
languages:
  en:
    contentDir: content
    languageName: R-TeX-WSL2-Dropbox
    weight: 1
  kr:
    contentDir: content.kr
    languageName: Korean
    weight: 2
  ru:
    contentDir: content.ru
    languageName: Russian
    weight: 3
  zh:
    contentDir: content.zh
    languageName: Chinese
    weight: 4
menu:
  after:
    - name: Github
      url: https://github.com/binomPricing/WSL2
      weight: 10
    - name: Hugo Themes
      url: https://themes.gohugo.io/hugo-book/
      weight: 20
params:
  BookComments: yes
  BookDateFormat: January 2, 2006
  BookEditPath: edit/main/exampleSite
  BookPortableLinks: yes
  BookRepo: https://github.com/alex-shpak/hugo-book
  BookSearch: yes
  BookSection: docs
  BookServiceWorker: yes
  BookTheme: light
  BookToC: yes
  BookTranslatedOnly: no
